name: dashcam_viewer
description: OpenPilot Dashcam Viewer - Cross-platform app for viewing dashcam videos with native HEVC support

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Navigation
  cupertino_icons: ^1.0.2
  go_router: ^14.0.0

  # State Management
  provider: ^6.1.0

  # HTTP Client
  http: ^1.1.0
  dio: ^5.4.0

  # Video Player with HEVC support
  video_player: ^2.8.0
  chewie: ^1.7.0

  # Platform specific video players for better HEVC support
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4

  # File handling
  path_provider: ^2.1.0
  path: ^1.8.3

  # JSON serialization
  json_annotation: ^4.8.1

  # Date/Time handling
  intl: ^0.19.0

  # Logging
  logger: ^2.0.2

  # Platform detection
  universal_platform: ^1.0.0+1

  # Desktop window management
  window_manager: ^0.3.7

  # Shared preferences
  shared_preferences: ^2.2.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
